/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as GeminiPreviewRouteImport } from './routes/gemini-preview'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as IndexRouteImport } from './routes/index'

const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const GeminiPreviewRoute = GeminiPreviewRouteImport.update({
  id: '/gemini-preview',
  path: '/gemini-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/gemini-preview': typeof GeminiPreviewRoute
  '/metrics': typeof MetricsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/gemini-preview': typeof GeminiPreviewRoute
  '/metrics': typeof MetricsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/gemini-preview': typeof GeminiPreviewRoute
  '/metrics': typeof MetricsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audio' | '/gemini-preview' | '/metrics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audio' | '/gemini-preview' | '/metrics'
  id: '__root__' | '/' | '/audio' | '/gemini-preview' | '/metrics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioRoute: typeof AudioRoute
  GeminiPreviewRoute: typeof GeminiPreviewRoute
  MetricsRoute: typeof MetricsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gemini-preview': {
      id: '/gemini-preview'
      path: '/gemini-preview'
      fullPath: '/gemini-preview'
      preLoaderRoute: typeof GeminiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioRoute: AudioRoute,
  GeminiPreviewRoute: GeminiPreviewRoute,
  MetricsRoute: MetricsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
